### ISSUE TITLE
Question: how to specify what to increment

### ISSUE THREAD

**Issue by LiorBanai** [remorses/bump-version#4]
Hi,
I would like to use this action but not sure how to setup it correctly.
How do I specific what to increment (major,minor, path)?  Can this be an manual triggered like 
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/#:~:text=You%20can%20now%20create%20workflows,the%20workflow%20is%20run%20on.

**Comment by remorses** [comment]
It does only patch bumps

I use this actions to always create a new version for every push, this way i can use the code just pushed on other projects

If i want to do a major bump i just change the version in VERSION file

**Comment by remorses** [comment]
I never tried `workflow_dispatch`, it should work i think

**Comment by LiorBanai** [comment]
Oh I see. Thanks!
