### ISSUE TITLE
error when VERSION file not found

### ISSUE THREAD

**Issue by adripo** [remorses/bump-version#5]
I tried to execute the job without a version file and returned this error.

`(node:2381) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './VERSION'`

I suggest to create the file with version 1.0.0 if it doesn't exist.

**Comment by ivanlynch** [comment]
I have the same issue, any update?

**Comment by eliran-mesika** [comment]
did you run  - uses: actions/checkout@v2 before ?
