### ISSUE TITLE
Git Commit Avatar is...Unexpected

### ISSUE THREAD

**Issue by chriswsh** [remorses/bump-version#8]
Are you aware that the commit history appears to be a user with this profile?

https://github.com/bump-version

That could cause problems, or cost someone their job.

**Comment by remorses** [comment]
Yeah it started as a joke but now I lost access to the account 😂

**Comment by remorses** [comment]
Now it should be fixed, hope it didn't cost your job

**Comment by chriswsh** [comment]
No, it was fine. Mostly unexpected, and we weren't sure if someone else had noticed the user wasn't registered and did that as a pranky way to highlight a potential security risk.

Thanks for changing it.
